[phases.setup]
aptPkgs = ["ffmpeg", "libavcodec-extra", "libavdevice58", "libavfilter7", "libavformat58", "libavutil56", "libpostproc55", "libswresample3", "libswscale5"]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[phases.start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 4 --timeout 120"
